# docker-compose.yml

services:

  nginx:
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    network_mode: host
    depends_on:
      - game
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/www:/var/www/certbot:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem:ro

  game:
    image: ghcr.io/peraperaquest/peraperaquest:latest
    container_name: game
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/www:/var/www/certbot
      - ./nginx/certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew \
                 --webroot \
                 --webroot-path=/var/www/certbot;
               sleep 12h & wait $${!};
             done"
