# docker-compose.yml

services:

  nginx:
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/www:/var/www/certbot:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem:ro
    depends_on:
      - monban-kun
      - game
    networks:
      - webnet

  monban-kun:
    image: ghcr.io/peraperaquest/monban-kun:latest
    container_name: monban-kun
    expose:
      - "3000:3000"
    env_file:
      - ./env.monban
    networks:
      - webnet

  game:
    image: ghcr.io/peraperaquest/peraperaquest:latest
    container_name: game
    expose:
      - "8080:8080"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/www:/var/www/certbot
      - ./nginx/certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; 
             while :; do 
               certbot renew --webroot --webroot-path=/var/www/certbot; 
               sleep 12h & wait $${!}; 
             done"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
