version: '3.8'

services:

  nginx:
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/www:/var/www/certbot:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - game

  game:
    image: ghcr.io/peraperaquest/peraperaquest:latest
    container_name: game
    expose:
      - "8080"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/www:/var/www/certbot
      - ./nginx/certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; 
             while :; do 
               certbot renew --webroot --webroot-path=/var/www/certbot; 
               sleep 12h & wait $${!}; 
             done"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
